//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _219_Pogosyan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issuance_of_books
    {
        public int ID { get; set; }
        public System.DateTime Date_of_issue { get; set; }
        public System.DateTime Date_of_return { get; set; }
        public int ID_Instances { get; set; }
    
        public virtual Instances Instances { get; set; }
    }
}
